# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: romannbroque <marvin@42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/02/24 09:47:47 by romannbroque      #+#    #+#              #
#    Updated: 2022/02/25 12:04:50 by romannbroque     ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

do_op : do_op.c checks.c errors.c operations.c get_n.c utilities.c clean_arg.c display.c
	gcc -Weverythin -o do_op *.c
