# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: romannbroque <marvin@42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/02 17:02:40 by romannbroque      #+#    #+#              #
#    Updated: 2022/03/04 09:44:53 by romannbroque     ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

binary_tree: binary_tree.c create_struct.c route.c display_route.c edit.c
	gcc -Wall -Wextra -Werror -o binary_tree *.c
