# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: romannbroque <marvin@42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/04 10:54:19 by romannbroque      #+#    #+#              #
#    Updated: 2022/03/05 18:30:03 by romannbroque     ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

linked_list : linked_list.c struct.c display.c get_info.c pop.c push.c reverse.c
	gcc -Wall -Werror -Wextra -o linked_list *.c
