# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: romannbroque <marvin@42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/02/16 22:39:17 by romannbroque      #+#    #+#              #
#    Updated: 2022/02/16 23:28:56 by romannbroque     ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

rush-1: rush-1.c display.c initialisation.c lexing.c part_check.c resolution.c utilities.c
	gcc -Wall -Wextra -Werror -o rush-1 *.c
